export type AdminLocale = "es-US" | "en-US";

const STORAGE_KEY = "kids.admin_locale.v1";

const english: Record<string, string> = {
  "Resumen": "Overview",
  "Huecos": "Gaps",
  "Cobertura": "Coverage",
  "Actividades": "Activities",
  "Creación IA": "AI creation",
  "Revisiones": "Reviews",
  "Pilotos": "Pilots",
  "Feedback familiar": "Family feedback",
  "Operaciones IA": "AI operations",
  "Proveedores y modelos": "Providers and models",
  "Personas y permisos": "People and permissions",
  "Incidentes": "Incidents",
  "Auditoría": "Audit",
  "Configuración": "Settings",
  "Alta": "High",
  "Media": "Medium",
  "Seguridad": "Safety",
  "Editorial": "Editorial",
  "Piloto": "Pilot",
  "Revisión": "Review",
  "Incidente": "Incident",
  "Familias": "Families",
  "Configura la primera cohorte de familias": "Configure the first family cohort",
  "Explicados por celda": "Explained by cell",
  "Gasto del mes": "Monthly spend",
  "Incidentes abiertos": "Open incidents",
  "Siguiente mejor acción": "Next best action",
  "Cola priorizada": "Prioritized queue",
  "pendientes": "pending",
  "Sin acciones visibles para este perfil.": "No visible actions for this role.",
  "Salud del sistema": "System health",
  "Contención requerida": "Containment required",
  "Controles técnicos activos": "Technical controls active",
  "Contratos V2 con gates de CI": "V2 contracts with CI gates",
  "rutas con evaluación aprobada": "routes with a passing evaluation",
  "Piloto activo": "Pilot active",
  "Piloto real pendiente": "Real pilot pending",
  "Especialista activo": "Specialist active",
  "Especialistas pendientes": "Specialists pending",
  "No se pudo guardar el objetivo": "The target could not be saved",
  "CAT-001 · cobertura efectiva": "CAT-001 · effective coverage",
  "Mapa del catálogo": "Catalog map",
  "Una secundaria validada aporta 0.5; un borrador no cubre el catálogo.": "A validated secondary area contributes 0.5; a draft does not count as catalog coverage.",
  "Cubierto": "Covered",
  "Parcial": "Partial",
  "Vacío": "Empty",
  "Área": "Area",
  "primaria ·": "primary ·",
  "secundaria": "secondary",
  "act. · meta": "act. · target",
  "Celda cubierta": "Covered cell",
  "de": "of",
  "cobertura efectiva": "effective coverage",
  "Esta celda alcanza el objetivo vigente.": "This cell reaches the current target.",
  "Demanda": "Demand",
  "Calidad": "Quality",
  "Riesgo máximo sugerido": "Suggested maximum risk",
  "Casi cubren este hueco": "Near matches for this gap",
  "Ninguna actividad existente se aproxima a esta combinación.": "No existing activity is close to this combination.",
  "No cubre toda la banda de edad": "Does not cover the full age band",
  "Aún no está publicada ni lista para piloto": "Not published or pilot-ready yet",
  "Falta un idioma revisado": "A reviewed language is missing",
  "Riesgo D bloqueado": "Risk D is blocked",
  "Falta especialista independiente": "Independent specialist is missing",
  "Falta perfil de cobertura": "Coverage profile is missing",
  "Objetivo vigente": "Current target",
  "Guardando…": "Saving…",
  "Guardar nueva versión": "Save new version",
  "El valor anterior se conserva en el historial.": "The previous value remains in history.",
  "Crear para cubrir este hueco": "Create to cover this gap",
  "El brief será editable y la IA no podrá publicar.": "The brief will be editable and AI cannot publish.",
  "Versiones exactas": "Exact versions",
  "Biblioteca editorial": "Editorial library",
  "Buscar actividad": "Search activities",
  "Actividad": "Activity",
  "Edad": "Age",
  "Riesgo": "Risk",
  "Estado": "State",
  "No hay versiones que coincidan": "No matching versions",
  "versiones visibles · el estado y hash vienen del backend": "visible versions · state and hash come from the backend",
  "No se pudo investigar": "Research could not be completed",
  "No se pudo añadir la fuente": "The source could not be added",
  "No se pudo avanzar": "The job could not advance",
  "No se pudo completar el índice RAG": "The RAG index could not be completed",
  "Fábrica asistida": "Assisted factory",
  "Trabajo editorial": "Editorial job",
  "sin iniciar": "not started",
  "Aún no hay trabajos": "There are no jobs yet",
  "Empieza desde un hueco verificable; cada etapa genera un artefacto pequeño y auditable.": "Start from a verifiable gap; every stage produces a small, auditable artifact.",
  "Trabajo": "Job",
  "Fuentes elegibles:": "Eligible sources:",
  "Buscar ejemplos públicos": "Search public examples",
  "Ej. actividad de física 5–6 años": "E.g. physics activity for ages 5–6",
  "Investigar": "Research",
  "El buscador descubre candidatos. El owner debe abrir la página exacta y verificar sus derechos.": "Search discovers candidates. The owner must open the exact page and verify its rights.",
  "Verificar fuente exacta": "Verify exact source",
  "Licencia": "License",
  "Abrí el recurso exacto y verifiqué esta licencia": "I opened the exact resource and verified this license",
  "Añadir evidencia": "Add evidence",
  "Procesando…": "Processing…",
  "Avanzar una etapa": "Advance one stage",
  "Reintentar índice RAG": "Retry RAG indexing",
  "Huecos prioritarios": "Priority gaps",
  "Crear con propósito": "Create with purpose",
  "Explica al menos un hallazgo para devolver o bloquear.": "Explain at least one finding before returning or blocking.",
  "Completa el checklist de evidencia antes de firmar.": "Complete the evidence checklist before signing.",
  "No se pudo registrar la revisión": "The review could not be recorded",
  "No se pudo asignar la revisión": "The review could not be assigned",
  "Trabajo humano": "Human work",
  "Mis revisiones asignadas": "My assigned reviews",
  "Puertas editoriales": "Editorial gates",
  "pendiente": "pending",
  "sin cola": "empty queue",
  "Asignar revisión profesional": "Assign professional review",
  "Especialista": "Specialist",
  "Selecciona": "Select",
  "Puerta": "Gate",
  "Fecha límite": "Due date",
  "Asignar versión exacta": "Assign exact version",
  "Primero invita un especialista": "Invite a specialist first",
  "Versión exacta": "Exact version",
  "Aún sin compilar": "Not compiled yet",
  "Hash de contenido": "Content hash",
  "Pendiente": "Pending",
  "Fuentes elegibles": "Eligible sources",
  "Etapas con evidencia": "Stages with evidence",
  "Hallazgos de críticos IA — no son aprobación": "AI critic findings — not an approval",
  "independiente obligatoria para riesgo C": "independent review required for risk C",
  "Compara la evidencia y registra una decisión humana explícita.": "Compare the evidence and record an explicit human decision.",
  "Esta puerta no está asignada a tu perfil.": "This gate is not assigned to your role.",
  "Asignada a": "Assigned to",
  "independiente": "independent",
  "interna": "internal",
  "Última decisión:": "Latest decision:",
  "Nueva decisión": "New decision",
  "Revisar": "Review",
  "Decisión ·": "Decision ·",
  "Esta firma se asociará a": "This signature will be linked to",
  "y al hash": "and hash",
  "Confirmé la versión y el hash exactos.": "I confirmed the exact version and hash.",
  "Revisé fuentes, artefactos y hallazgos disponibles.": "I reviewed available sources, artifacts, and findings.",
  "Evalué solo mi ámbito profesional y los controles de seguridad aplicables.": "I assessed only my professional scope and the applicable safety controls.",
  "Decisión": "Decision",
  "Aprobar esta puerta": "Approve this gate",
  "Devolver para cambios": "Return for changes",
  "Bloquear por hallazgo crítico": "Block for a critical finding",
  "Hallazgos — uno por línea": "Findings — one per line",
  "Describe evidencia, correcciones o riesgo observado.": "Describe evidence, corrections, or observed risk.",
  "Registrar decisión humana": "Record human decision",
  "Cancelar": "Cancel",
  "No hay trabajos asignados listos para revisión": "No assigned jobs are ready for review",
  "La revisión del owner queda identificada como interna; nunca se presenta como firma independiente.": "The owner's review is identified as internal and is never presented as an independent signature.",
  "No se pudo actualizar el piloto": "The pilot could not be updated",
  "Validación real": "Real validation",
  "Cohortes privadas": "Private cohorts",
  "sin cohorte": "no cohort",
  "Nombre de la cohorte": "Cohort name",
  "Familias amigas · septiembre": "Family friends · September",
  "Crear cohorte": "Create cohort",
  "Cohorte": "Cohort",
  "Aprobar versión exacta para piloto": "Approve exact version for pilot",
  "Añadir": "Add",
  "a la cohorte": "to cohort",
  "ID de familia tester": "Tester family ID",
  "UUID entregado por la familia": "UUID supplied by the family",
  "Añadir familia": "Add family",
  "Activar cohorte": "Activate cohort",
  "Verificar gates y publicar": "Verify gates and publish",
  "familias ·": "families ·",
  "versiones exactas": "exact versions",
  "Los conteos manuales no publican nada. Cada sesión cerrada y su feedback quedan ligados al hash exacto.": "Manual counts publish nothing. Every closed session and its feedback remain linked to the exact hash.",
  "Gate comercial": "Commercial gate",
  "Sin falsos positivos": "No false positives",
  "≥5 ejecuciones reales": "≥5 real runs",
  "≥2 familias y un adulto externo": "≥2 families and one external adult",
  "≥70% cierre útil y duración adecuada": "≥70% useful completion and appropriate duration",
  "≥80% utilidad": "≥80% usefulness",
  "0 incidentes críticos": "0 critical incidents",
  "La base de datos vuelve a verificar derechos, traducciones, revisiones, RAG y evidencia antes de publicar.": "The database rechecks rights, translations, reviews, RAG, and evidence before publishing.",
  "Voz adulta": "Adult voice",
  "Feedback del producto completo": "Whole-product feedback",
  "Todo": "All",
  "Errores": "Errors",
  "útil": "useful",
  "no útil": "not useful",
  "Sin comentario libre": "No free-text comment",
  "experiencia general": "overall experience",
  "· caduca": "· expires",
  "incidente": "incident",
  "Sin comentarios en este filtro": "No feedback in this filter",
  "El piloto recopila utilidad, pantalla, versión e idioma. El texto libre se redacta y elimina a los 90 días.": "The pilot collects usefulness, screen, version, and language. Free text is redacted and deleted after 90 days.",
  "No se pudo activar la ruta": "The route could not be activated",
  "No se pudieron cargar las métricas": "Metrics could not be loaded",
  "Consultas": "Requests",
  "Costo": "Cost",
  "Latencia p95": "p95 latency",
  "Ventana seleccionada": "Selected window",
  "Fallbacks": "Fallbacks",
  "Uso normalizado": "Normalized usage",
  "Filtrar métricas": "Filter metrics",
  "Operación": "Operation",
  "Todas": "All",
  "Proveedor": "Provider",
  "Todos": "All",
  "Modelo": "Model",
  "ID exacto": "Exact ID",
  "Entorno": "Environment",
  "Idioma": "Language",
  "Aplicar filtros": "Apply filters",
  "Los adultos y familias se cuentan mediante identificadores seudonimizados; prompts y respuestas no aparecen aquí.": "Adults and families are counted with pseudonymous identifiers; prompts and responses are not shown here.",
  "Endpoints y routing": "Endpoints and routing",
  "Cada operación selecciona proveedor, modelo y fallback sin desplegar código.": "Each operation selects a provider, model, and fallback without deploying code.",
  "Capacidad": "Capability",
  "Ruta activa": "Active route",
  "No usa IA": "Does not use AI",
  "Determinista": "Deterministic",
  "activa": "active",
  "sin IA": "no AI",
  "Editar": "Edit",
  "Editar ruta": "Edit route",
  "Nueva versión de política": "New policy version",
  "Deployment principal": "Primary deployment",
  "Fallback": "Fallback",
  "Sin fallback": "No fallback",
  "Upstreams OpenRouter": "OpenRouter upstreams",
  "Temperatura": "Temperature",
  "Razonamiento": "Reasoning",
  "Máx. salida": "Max output",
  "Tope USD/solicitud": "USD cap/request",
  "Timeout ms": "Timeout ms",
  "Canary %": "Canary %",
  "1. Compatibilidad local": "1. Local compatibility",
  "2. Fixtures live": "2. Live fixtures",
  "3. Golden del sistema": "3. System golden set",
  "4. Activación atómica": "4. Atomic activation",
  "Compatibilidad local": "Local compatibility",
  "Activación atómica": "Atomic activation",
  "Probando y evaluando…": "Testing and evaluating…",
  "Probar, evaluar y activar": "Test, evaluate, and activate",
  "En producción, la evaluación ejecuta llamadas reales y la versión anterior queda disponible para rollback.": "In production, evaluation makes real calls and the previous version remains available for rollback.",
  "No se pudo completar la operación": "The operation could not be completed",
  "Secretos write-only": "Write-only secrets",
  "Conexiones": "Connections",
  "+ Añadir": "+ Add",
  "Nombre": "Name",
  "URL base": "Base URL",
  "API key": "API key",
  "La clave se envía una vez, queda cifrada y nunca vuelve al navegador.": "The key is submitted once, encrypted, and never returned to the browser.",
  "Guardar conexión": "Save connection",
  "Clave ····": "Key ····",
  "sin comprobar": "not checked",
  "Gestionar": "Manage",
  "Presupuestos activos": "Active budgets",
  "advertencia": "warning",
  "pausa editorial": "editorial pause",
  "bloqueo no esencial": "non-essential block",
  "Alcance": "Scope",
  "operación": "operation",
  "proveedor": "provider",
  "modelo": "model",
  "entorno": "environment",
  "trabajo editorial": "editorial job",
  "Clave exacta": "Exact key",
  "all, proveedor/modelo, operation_key o UUID": "all, provider/model, operation_key, or UUID",
  "Periodo": "Period",
  "mes": "month",
  "día": "day",
  "trabajo (solo trabajo editorial)": "job (editorial jobs only)",
  "Límite USD": "USD limit",
  "Guardar presupuesto": "Save budget",
  "Modelos elegibles": "Eligible models",
  "Deployments": "Deployments",
  "Conexión": "Connection",
  "ID exacto del modelo": "Exact model ID",
  "Clases de datos": "Data classes",
  "Crear candidato": "Create candidate",
  "Verdad contable": "Accounting truth",
  "Tarifas con vigencia": "Effective-dated rates",
  "entrada $": "input $",
  "/M · salida $": "/M · output $",
  "Entrada / millón": "Input / million",
  "Caché / millón": "Cache / million",
  "Salida / millón": "Output / million",
  "Razonamiento / millón": "Reasoning / million",
  "Embedding / millón": "Embedding / million",
  "Fuente oficial": "Official source",
  "Registrar tarifa": "Register rate",
  "Conexión protegida": "Protected connection",
  "Probar conexión": "Test connection",
  "Nueva API key": "New API key",
  "Rotar clave": "Rotate key",
  "¿Revocar esta conexión y desactivar sus deployments?": "Revoke this connection and disable its deployments?",
  "Revocar conexión": "Revoke connection",
  "Estas operaciones requieren MFA y quedan auditadas. La clave nunca se puede revelar.": "These operations require MFA and are audited. The key can never be revealed.",
  "No se pudo actualizar el acceso": "Access could not be updated",
  "Acceso temporal registrado y auditado.": "Temporary access recorded and audited.",
  "Mínimo privilegio": "Least privilege",
  "MFA requerido": "MFA required",
  "sin dominios": "no domains",
  "Dominios asignados": "Assigned domains",
  "activo": "active",
  "inactivo": "inactive",
  "Activo": "Active",
  "Guardar": "Save",
  "Invitar administrador": "Invite administrator",
  "Correo del adulto": "Adult email",
  "Perfil": "Role",
  "Especialista editorial": "Editorial specialist",
  "Soporte": "Support",
  "Dominios, separados por coma": "Domains, comma-separated",
  "Enviar invitación": "Send invitation",
  "Los especialistas requieren al menos un dominio. Nadie recibe acceso a claves o costes salvo el owner.": "Specialists require at least one domain. Only the owner has access to keys or costs.",
  "Soporte justificado": "Justified support",
  "Acceso temporal a una familia": "Temporary access to one family",
  "Operador": "Operator",
  "ID de familia": "Family ID",
  "Motivo": "Reason",
  "Soporte solicitado por el adulto": "Support requested by the adult",
  "Expira": "Expires",
  "Conceder acceso": "Grant access",
  "El operador solo ve la familia autorizada, durante el plazo indicado. Cada concesión queda auditada.": "The operator sees only the authorized family for the stated period. Every grant is audited.",
  "No se pudo actualizar el incidente": "The incident could not be updated",
  "Seguridad y privacidad": "Safety and privacy",
  "abiertos": "open",
  "sin familia": "no family",
  "Producto general": "Whole product",
  "Sin incidentes activos": "No active incidents",
  "Un reporte crítico de seguridad retira inmediatamente nuevas recomendaciones de la versión afectada.": "A critical safety report immediately removes new recommendations for the affected version.",
  "contenido": "contained",
  "investigando": "investigating",
  "resuelto": "resolved",
  "Justificación": "Justification",
  "Guardar y auditar": "Save and audit",
  "Registro inmutable": "Immutable record",
  "Exportar CSV": "Export CSV",
  "actor:": "actor:",
  "Aún no hay eventos administrativos": "There are no administrative events yet",
  "Las mutaciones sensibles aparecerán aquí sin secretos, prompts ni respuestas.": "Sensitive mutations appear here without secrets, prompts, or responses.",
  "Selecciona al menos un idioma.": "Select at least one language.",
  "No se pudo guardar la configuración": "The settings could not be saved",
  "Producto · versión": "Product · version",
  "Configuración del piloto": "Pilot settings",
  "Marca": "Brand",
  "Idiomas activos": "Active languages",
  "Zona horaria": "Time zone",
  "Cada cambio crea una versión; nunca modifica silenciosamente una configuración histórica.": "Every change creates a version; it never silently changes historical settings.",
  "Fuera del piloto": "Outside the pilot",
  "Sin cuentas infantiles": "No child accounts",
  "Sin voz o fotografías": "No voice or photographs",
  "Sin comunidad": "No community",
  "Sin pagos en app": "No in-app payments",
  "No pudimos preparar MFA": "MFA could not be prepared",
  "Código no válido": "Invalid code",
  "Acceso administrativo": "Administrative access",
  "Verificación en dos pasos": "Two-step verification",
  "Introduce el código actual de tu aplicación autenticadora.": "Enter the current code from your authenticator app.",
  "Escanea el código con una aplicación TOTP. Esta configuración protege contenido, familias, proveedores y costes.": "Scan the code with a TOTP app. This setup protects content, families, providers, and costs.",
  "Preparando segundo factor…": "Preparing second factor…",
  "Código QR para configurar TOTP": "QR code for TOTP setup",
  "Clave manual": "Manual key",
  "Código de 6 dígitos": "6-digit code",
  "Verificando…": "Verifying…",
  "Verificar y abrir workspace": "Verify and open workspace",
  "Cerrar sesión": "Sign out",
  "No se pudo cargar el workspace": "The workspace could not be loaded",
  "Comprobando identidad administrativa…": "Checking administrative identity…",
  "Workspace no disponible": "Workspace unavailable",
  "Preparando workspace editorial…": "Preparing editorial workspace…",
  "Workspace administrativo": "Administrative workspace",
  "Vista de perfil": "Role preview",
  "Equipo": "Team",
  "Ver app familiar": "View family app",
  "Salir": "Sign out",
  "Física": "Physics",
  "Ingeniería": "Engineering",
  "Electricidad": "Electricity",
  "Matemáticas": "Mathematics",
  "Química segura": "Safe chemistry",
  "Biología y naturaleza": "Biology and nature",
  "Motricidad": "Motor skills",
  "Creatividad": "Creativity",
  "Pensamiento lógico": "Logical thinking",
  "Comunicación": "Communication",
  "Autorregulación": "Self-regulation",
  "Vida práctica": "Practical life",
  "Añade al menos una fuente exacta con derechos elegibles.": "Add at least one exact source with eligible rights.",
  "Falta una revisión profesional independiente.": "An independent professional review is missing.",
  "Añade una familia y una versión exacta.": "Add a family and an exact version."
};

let renderLocale: AdminLocale = "es-US";

export function adminLocaleFromLocation(): AdminLocale {
  const query = new URLSearchParams(window.location.search).get("lang");
  if (query === "en-US" || query === "es-US") return query;
  const stored = localStorage.getItem(STORAGE_KEY);
  return stored === "en-US" || stored === "es-US" ? stored : "es-US";
}

export function setAdminRenderLocale(locale: AdminLocale): void {
  renderLocale = locale;
}

export function persistAdminLocale(locale: AdminLocale): void {
  localStorage.setItem(STORAGE_KEY, locale);
  const url = new URL(window.location.href);
  url.searchParams.set("lang", locale);
  window.history.replaceState(window.history.state, "", `${url.pathname}${url.search}${url.hash}`);
}

function dynamicEnglish(value: string): string {
  return value
    .replace(/^(\d+) elegibles$/, "$1 eligible")
    .replace(/^de \$([\d.]+)$/, "of $$$1")
    .replace(/^(\d+) trabajos esperan decisión humana$/, "$1 jobs await a human decision")
    .replace(/^(\d+) trabajos en revisión$/, "$1 jobs under review")
    .replace(/^(\d+) comentarios visibles con acceso justificado$/, "$1 visible comments with justified access")
    .replace(/^La cobertura efectiva es ([\d.]+) de ([\d.]+)\.$/, "Effective coverage is $1 of $2.")
    .replace(/^No existe una actividad elegible de (.+) para (.+) años\.$/, (_match, area: string, ages: string) => `There is no eligible ${english[area] ?? area} activity for ages ${ages}.`)
    .replace(/^Versión (.+) activada\.$/, "Version $1 activated.")
    .replace(/^Invitación (.+) creada para (.+)\.$/, "Invitation $1 created for $2.")
    .replace(/^Trabajo creado para (.+)\.$/, "Job created for $1.")
    .replace(/^(\d+) adultos · (\d+) familias$/, "$1 adults · $2 families")
    .replace(/^(.+) · \$([\d.]+)\/consulta$/, "$1 · $$$2/request")
    .replace(/^(\d+) errores$/, "$1 errors")
    .replace(/^Hueco (.+)$/, "Gap $1");
}

export function adminText<T extends string>(value: T): T {
  if (renderLocale === "es-US") return value;
  return (english[value] ?? dynamicEnglish(value)) as T;
}
