import type { Locale } from "./types";

const en = {
  brandSub: "Grown-up guided", beforeStart: "Before you begin", togetherTitle: "Learn together, with an adult present.", togetherBody: "Kids Learning suggests family experiences. It is not designed for a child to use alone and it does not create child accounts.", consentTitle: "I understand that an adult guides every activity.", consentBody: "Safety, materials, and changes always require supervision.", continue: "Continue",
  home: "Your household", updateHome: "Update what works at home", homeQuestion: "What usually works at home?", familyName: "Family name", state: "State (US)", language: "Language", units: "Units", metric: "Metric", us: "US customary", min30: "30 minutes", min20: "20 minutes", lowMess: "Low mess", mediumMess: "Medium mess", kids12: "1–2 children", kids34: "3–4 children", stateEdit: "Changing the state requires new consent; other preferences can be saved now.", stateNew: "The state lets us apply the right consent rules. You can change other preferences later.",
  participants: "Participants", aliasesTitle: "Use nicknames, not full names.", nickname: "Nickname", age: "Age", remove: "Remove", addParticipant: "+ Add participant", saving: "Saving…", saveChanges: "Save changes", firstPlan: "See my first plan", noChildData: "We do not ask for a child's birth date, school, photo, or email.", saveFamilyError: "We could not save the family.",
  gate: "Adult gate", gateTitle: "Confirm the three matches", gateBody: "This friction helps keep an adult present. It does not legally verify age.", gateMismatch: "The matches do not correspond.", checking: "Checking…", unlock: "Unlock for 15 minutes",
  privatePilot: "Private pilot", feedback: "Feedback", pilotFamily: "Family pilot", feedbackTitle: "How is the experience going?", thanks: "Thank you. Your feedback was recorded.", retention: "Only the redacted text is kept and it expires after 90 days.", useful: "Was it useful?", yes: "Yes", no: "No", type: "Type", product: "Product", content: "Content", error: "Error", safety: "Safety", privacy: "Privacy", optionalComment: "Optional comment", commentPlaceholder: "Tell us what worked or where things got stuck. Do not include names, emails, or child data.", sendComment: "Send feedback", feedbackError: "We could not send the feedback.",
  mess: "mess", years: "years", risk: "Risk", viewActivity: "View activity", prepareActivity: "Prepare activity", familyPlan: "Family plan", todayTitle: "One clear idea for learning together.", todayBody: "Chosen for age, time, materials, and preferences. You decide whether it fits today.", why: "Why this one?", publishedRules: "Published rules", noMatch: "No published activity fits yet", noDrafts: "The administrator will see this gap. Drafts are never shown to families.", guideWorks: "The guide always works without AI.", companionPurpose: "The companion troubleshoots or proposes changes that were already reviewed.",
  yourWeek: "Your week", flexiblePlan: "Flexible plan", planBody: "Choose any other published activity before starting. The exact version is pinned when the session begins.", today: "Today", next: "Next", weekend: "Weekend", later: "Later", suggested: "Suggested", ready: "Ready", browseAlternatives: "Browse alternatives",
  publishedCatalog: "Published catalog", explore: "Explore activities", exploreBody: "Only reviewed, eligible bilingual versions appear here.", all: "All", littleMess: "Low mess", oneChild: "1 child", riskA: "Risk A", noResults: "No published results", tryFilter: "Try a different filter.",
  observationsNotScores: "Observations, not scores", journey: "Your journey", journeyBody: "See what your family tried and noticed, without grading a child.", activitiesClosed: "activities closed", inProgress: "In progress", explainableHistory: "explainable history", noTrend: "not enough evidence for a trend", recentObservations: "Recent observations", noComment: "Close-out without a comment", firstObservation: "The first observation starts today", afterActivity: "After an activity you can save a close-out designed to take under 20 seconds.",
  adultControl: "Adult control", family: "Family", familyBody: "Minimal profiles, preferences, and privacy controls in one place.", people: "Participants", editPreferences: "Edit preferences", preferences: "Preferences", usualTime: "Usual time", locale: "Language", privacyData: "Privacy and data", processing: "Processing…", exportQueued: "Export request recorded.", deleteQueued: "Deletion request recorded.", reauthNeeded: "Recent authentication is required before recording this request.", reauthSent: "We sent a link to the adult's email. Open it and repeat the request.", reauthFailed: "We could not send the link. Try again.", exportData: "Export data", requestDelete: "Request deletion", sendReauth: "Send reauthentication link", recentAuth: "Requires recent authentication.", policyPrivacy: "Privacy", policyTerms: "Terms", policySafety: "Safety", signOut: "Sign out",
  preparationKicker: "Before the adult gate", preparationTitle: "Review and adapt the activity", preparationBody: "Check the published guide now. Use the companion button to describe what needs to change; nothing changes until you confirm an approved option.", selectedPeople: "Selected participants", readyToStart: "Ready to start?", openAdultGate: "Confirm adult presence and start", backToCatalog: "Choose another activity", previewError: "We could not prepare this exact activity version.",
  noBlocks: "Activity has no published steps", back: "Back", exit: "Exit", exactVersion: "Exact version", currentStep: "Current step", stepSaveError: "We could not save the step.", closeSaveError: "We could not save the close-out.", previous: "Previous", closeActivity: "Close activity", nextStep: "Next step", closeoutKicker: "Close-out · designed for under 20 seconds", closeoutTitle: "How did it go today?", worked: "Worked", partly: "Partly", notToday: "Not today", optionalObservation: "One optional observation", noticed: "We noticed…", exportDeleteNote: "You can request export or deletion from Family.",
  preparing: "Preparing your family plan…", loadTitle: "We could not load your family", retry: "Try again", completeProfile: "Complete the family profile", todayNav: "Today", planNav: "Plan", exploreNav: "Explore", journeyNav: "Journey", familyNav: "Family", gateError: "We could not prepare the adult gate.", offlineActive: "Offline: this downloaded session remains available.", offlineQueued: "Saved securely on this device; it will sync when the connection returns.", syncPending: "change pending synchronization", syncPendingPlural: "changes pending synchronization",
} as const;

type FamilyCopy = { [K in keyof typeof en]: string };

const es: FamilyCopy = {
  brandSub: "Guiado por adultos", beforeStart: "Antes de empezar", togetherTitle: "Aprender juntos, con un adulto presente.", togetherBody: "Kids Learning propone experiencias familiares. No es una aplicación para que un niño use a solas y no crea cuentas infantiles.", consentTitle: "Entiendo que un adulto guía cada actividad.", consentBody: "La seguridad, los materiales y los cambios siempre requieren supervisión.", continue: "Continuar",
  home: "Tu hogar", updateHome: "Actualiza lo que funciona en casa", homeQuestion: "¿Qué suele funcionar en casa?", familyName: "Nombre familiar", state: "Estado (EE. UU.)", language: "Idioma", units: "Unidades", metric: "Métricas", us: "EE. UU.", min30: "30 minutos", min20: "20 minutos", lowMess: "Poco desorden", mediumMess: "Desorden medio", kids12: "1–2 niños", kids34: "3–4 niños", stateEdit: "Cambiar el estado requiere un nuevo consentimiento; las demás preferencias se guardan ahora.", stateNew: "El estado permite aplicar las reglas de consentimiento correctas. Puedes cambiar las demás preferencias después.",
  participants: "Participantes", aliasesTitle: "Usa apodos, no nombres completos.", nickname: "Apodo", age: "Edad", remove: "Quitar", addParticipant: "+ Añadir participante", saving: "Guardando…", saveChanges: "Guardar cambios", firstPlan: "Ver mi primer plan", noChildData: "No pedimos fecha de nacimiento, escuela, foto ni correo del niño.", saveFamilyError: "No pudimos guardar la familia.",
  gate: "Puerta para adultos", gateTitle: "Confirma las tres asociaciones", gateBody: "Esta fricción ayuda a mantener a un adulto presente. No verifica legalmente la edad.", gateMismatch: "Las asociaciones no coinciden.", checking: "Comprobando…", unlock: "Desbloquear 15 minutos",
  privatePilot: "Piloto privado", feedback: "Feedback", pilotFamily: "Piloto familiar", feedbackTitle: "¿Cómo va la experiencia?", thanks: "Gracias. Tu comentario quedó registrado.", retention: "Solo se guarda el texto redactado y caduca a los 90 días.", useful: "¿Te resultó útil?", yes: "Sí", no: "No", type: "Tipo", product: "Producto", content: "Contenido", error: "Error", safety: "Seguridad", privacy: "Privacidad", optionalComment: "Comentario opcional", commentPlaceholder: "Cuéntanos qué funcionó o qué se trabó. No incluyas nombres, correos ni datos del niño.", sendComment: "Enviar comentario", feedbackError: "No pudimos enviar el comentario.",
  mess: "desorden", years: "años", risk: "Riesgo", viewActivity: "Ver actividad", prepareActivity: "Preparar actividad", familyPlan: "Plan de familia", todayTitle: "Una idea clara para aprender juntos.", todayBody: "Elegida por edad, tiempo, materiales y preferencias. Tú decides si encaja hoy.", why: "¿Por qué esta?", publishedRules: "Reglas publicadas", noMatch: "Aún no hay una actividad publicada que encaje", noDrafts: "El administrador verá este hueco. Ningún borrador se muestra a familias.", guideWorks: "La guía siempre funciona sin IA.", companionPurpose: "El acompañante resuelve problemas o propone cambios ya revisados.",
  yourWeek: "Tu semana", flexiblePlan: "Plan flexible", planBody: "Elige cualquier otra actividad publicada antes de iniciar. La versión exacta queda fijada al comenzar.", today: "Hoy", next: "Próxima", weekend: "Fin de semana", later: "Después", suggested: "Sugerido", ready: "Listo", browseAlternatives: "Explorar alternativas",
  publishedCatalog: "Catálogo publicado", explore: "Explorar actividades", exploreBody: "Solo mostramos versiones bilingües, revisadas y elegibles.", all: "Todo", littleMess: "Poco desorden", oneChild: "1 niño", riskA: "Riesgo A", noResults: "Sin resultados publicados", tryFilter: "Prueba otro filtro.",
  observationsNotScores: "Observaciones, no notas", journey: "Tu recorrido", journeyBody: "Aquí verás lo que probaron y notaron, sin calificar al niño.", activitiesClosed: "actividades cerradas", inProgress: "En curso", explainableHistory: "historial explicable", noTrend: "todavía sin evidencia suficiente para una tendencia", recentObservations: "Observaciones recientes", noComment: "Cierre sin comentario", firstObservation: "La primera observación empieza hoy", afterActivity: "Después de una actividad podrás guardar un cierre diseñado para tomar menos de 20 segundos.",
  adultControl: "Control adulto", family: "Familia", familyBody: "Perfiles mínimos, preferencias y privacidad en un solo lugar.", people: "Participantes", editPreferences: "Editar preferencias", preferences: "Preferencias", usualTime: "Tiempo habitual", locale: "Idioma", privacyData: "Privacidad y datos", processing: "Procesando…", exportQueued: "Solicitud de exportación registrada.", deleteQueued: "Solicitud de eliminación registrada.", reauthNeeded: "Necesitamos una autenticación reciente antes de registrar esta solicitud.", reauthSent: "Enviamos un enlace al correo del adulto. Ábrelo y repite la solicitud.", reauthFailed: "No pudimos enviar el enlace. Inténtalo de nuevo.", exportData: "Exportar datos", requestDelete: "Solicitar eliminación", sendReauth: "Enviar enlace de reautenticación", recentAuth: "Requiere autenticación reciente.", policyPrivacy: "Privacidad", policyTerms: "Términos", policySafety: "Seguridad", signOut: "Cerrar sesión",
  preparationKicker: "Antes de la puerta adulta", preparationTitle: "Revisa y adapta la actividad", preparationBody: "Comprueba ahora la guía publicada. Usa el botón del acompañante para explicar qué necesitas cambiar; nada se modifica hasta que confirmes una opción aprobada.", selectedPeople: "Participantes elegidos", readyToStart: "¿Listos para comenzar?", openAdultGate: "Confirmar presencia adulta e iniciar", backToCatalog: "Elegir otra actividad", previewError: "No pudimos preparar esta versión exacta de la actividad.",
  noBlocks: "Actividad sin pasos publicados", back: "Volver", exit: "Salir", exactVersion: "Versión exacta", currentStep: "Paso actual", stepSaveError: "No pudimos guardar el paso.", closeSaveError: "No pudimos guardar el cierre.", previous: "Anterior", closeActivity: "Cerrar actividad", nextStep: "Siguiente paso", closeoutKicker: "Cierre · diseñado para menos de 20 segundos", closeoutTitle: "¿Cómo resultó hoy?", worked: "Funcionó", partly: "En parte", notToday: "Hoy no", optionalObservation: "Una observación opcional", noticed: "Notamos que…", exportDeleteNote: "Puedes solicitar exportación o eliminación desde Familia.",
  preparing: "Preparando tu plan familiar…", loadTitle: "No pudimos cargar tu familia", retry: "Reintentar", completeProfile: "Completa el perfil familiar", todayNav: "Hoy", planNav: "Plan", exploreNav: "Explorar", journeyNav: "Recorrido", familyNav: "Familia", gateError: "No pudimos preparar la puerta adulta.", offlineActive: "Sin conexión: esta sesión descargada sigue disponible.", offlineQueued: "Guardado de forma segura en este dispositivo; se sincronizará cuando vuelva la conexión.", syncPending: "cambio pendiente de sincronizar", syncPendingPlural: "cambios pendientes de sincronizar",
};

export const familyProductCopy: Record<Locale, FamilyCopy> = { "en-US": en, "es-US": es };
