import { FormEvent, useEffect, useMemo, useState } from "react";
import {
  createAdultGate, DEMO_FAMILY_ID, DEMO_MODE, getCatalog, getExperience,
  getFamilyOverview, requestPrivacyAction, sendFamilyFeedback, setupFamily,
  startFamilySession, updateSessionProgress, closeFamilySession, verifyAdultGate
} from "./api";
import { renderBlock } from "./blocks";
import { Companion } from "./Companion";
import type { AdultGateChallenge, CatalogCard, ExperienceView, FamilyOverview, FamilyProfile, FamilySession, JourneyView, Locale } from "./types";
import { requestReauthentication, signOut, supabase } from "./auth";
import { Login } from "./Login";

type FamilyTab = "today" | "plan" | "explore" | "journey" | "family";
type SetupInput = Parameters<typeof setupFamily>[0];

function Brand() { return <a className="family-brand" href="/"><span className="brand-mark" aria-hidden="true"><i/><i/><i/></span><span><strong>Kids Learning</strong><small>Grown-up guided</small></span></a>; }

function Card({ card, compact = false, onStart }: { card: CatalogCard; compact?: boolean; onStart: (card: CatalogCard) => void }) {
  return <article className={`family-activity-card ${compact ? "compact" : ""}`}><div className={`activity-art art-${Number(card.activityVersionId.replace(/\D/g, "").slice(-2)) % 4}`}><span>{card.title.split(" ").map(word => word[0]).join("").slice(0, 2)}</span><small>{card.mess} mess</small></div><div className="activity-card-body"><div className="card-tags"><span>{card.minutes} min</span><span>{card.age[0]}–{card.age[1]} años</span><span>Riesgo {card.risk}</span></div><h3>{card.title}</h3><p>{card.summary}</p><button className="button primary" onClick={() => onStart(card)}>{compact ? "Ver actividad" : "Preparar actividad"}</button></div></article>;
}

function Onboarding({ onDone, onClose, initial }: { onDone: (input: SetupInput) => Promise<void>; onClose?: () => void; initial?: FamilyProfile }) {
  const editing = Boolean(initial);
  const [step, setStep] = useState(editing ? 1 : 0), [adultLed, setAdultLed] = useState(editing), [busy, setBusy] = useState(false);
  const [aliases, setAliases] = useState(initial?.learners.map(item => item.alias) ?? ["Explorer 1", "Builder 2"]);
  const [ageBands, setAgeBands] = useState<Array<"5-6" | "7-8" | "9-10">>(initial?.learners.map(item => item.ageBand) ?? ["5-6", "7-8"]);
  const [learnerIds, setLearnerIds] = useState<Array<string | null>>(initial?.learners.map(item => item.learnerId) ?? [null, null]);
  const [removedLearnerIds, setRemovedLearnerIds] = useState<string[]>([]);
  const [minutes, setMinutes] = useState(initial?.preferences.minutes ?? 30), [participants, setParticipants] = useState(initial?.preferences.participants ?? 2);
  const [mess, setMess] = useState<"low" | "medium" | "high">(initial?.preferences.mess ?? "low"), [familyName, setFamilyName] = useState(initial?.familyName ?? "Mi familia"), [stateCode, setStateCode] = useState(initial?.stateCode ?? "FL"), [locale, setLocale] = useState<Locale>(initial?.locale ?? "es-US"), [units, setUnits] = useState<"metric" | "us_customary">(initial?.units ?? "metric"), [error, setError] = useState<string | null>(null);
  function removeLearner(index: number) { const id = learnerIds[index]; if (id) setRemovedLearnerIds(old => [...old, id]); setAliases(old => old.filter((_, i) => i !== index)); setAgeBands(old => old.filter((_, i) => i !== index)); setLearnerIds(old => old.filter((_, i) => i !== index)); }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { await onDone({ familyName, stateCode: stateCode.toUpperCase(), locale, units, timezone: initial?.timezone ?? (Intl.DateTimeFormat().resolvedOptions().timeZone || "America/New_York"), learnerAliases: aliases, ageBands, learnerIds, removedLearnerIds, participants, minutes, mess }); } catch (reason) { setError(reason instanceof Error ? reason.message : "No pudimos guardar la familia."); } finally { setBusy(false); } }
  return <div className="family-modal full"><section className="onboarding-card">{onClose && <button className="modal-close" onClick={onClose}>×</button>}<Brand/><div className="onboarding-progress">{[0, 1, 2].map(index => <i className={index <= step ? "active" : ""} key={index}/>)}</div>
    {step === 0 && <div className="onboarding-step"><p className="eyebrow">Antes de empezar</p><h1>Aprender juntos, con un adulto presente.</h1><p>Kids Learning propone experiencias familiares. No es una aplicación para que un niño use a solas y no crea cuentas infantiles.</p><label className="consent-row"><input type="checkbox" checked={adultLed} onChange={event => setAdultLed(event.target.checked)}/><span><strong>Entiendo que un adulto guía cada actividad.</strong><small>La seguridad, los materiales y los cambios siempre requieren supervisión.</small></span></label><button className="button primary block" disabled={!adultLed} onClick={() => setStep(1)}>Continuar</button></div>}
    {step === 1 && <div className="onboarding-step"><p className="eyebrow">Tu hogar</p><h1>{editing ? "Actualiza lo que funciona en casa" : "¿Qué suele funcionar en casa?"}</h1><div className="learner-line"><label>Nombre familiar<input value={familyName} onChange={event => setFamilyName(event.target.value)} maxLength={80}/></label><label>Estado (EE. UU.)<input value={stateCode} disabled={editing} onChange={event => setStateCode(event.target.value.replace(/[^A-Za-z]/g, "").slice(0, 2))} maxLength={2}/></label></div><div className="learner-line"><label>Idioma<select value={locale} onChange={event => setLocale(event.target.value as Locale)}><option value="es-US">Español</option><option value="en-US">English</option></select></label><label>Unidades<select value={units} onChange={event => setUnits(event.target.value as typeof units)}><option value="metric">Métricas</option><option value="us_customary">EE. UU.</option></select></label></div><div className="choice-grid"><button className={minutes === 30 ? "selected" : ""} onClick={() => setMinutes(30)}>30 minutos</button><button className={minutes === 20 ? "selected" : ""} onClick={() => setMinutes(20)}>20 minutos</button><button className={mess === "low" ? "selected" : ""} onClick={() => setMess("low")}>Poco desorden</button><button className={mess === "medium" ? "selected" : ""} onClick={() => setMess("medium")}>Desorden medio</button><button className={participants === 2 ? "selected" : ""} onClick={() => setParticipants(2)}>1–2 niños</button><button className={participants === 4 ? "selected" : ""} onClick={() => setParticipants(4)}>3–4 niños</button></div><p className="privacy-note">{editing ? "Cambiar el estado requiere un nuevo consentimiento; las demás preferencias se guardan ahora." : "El estado permite aplicar reglas de consentimiento correctas. Puedes cambiar las demás preferencias después."}</p><button className="button primary block" disabled={stateCode.length !== 2 || !familyName.trim()} onClick={() => setStep(2)}>Continuar</button></div>}
    {step === 2 && <form className="onboarding-step" onSubmit={submit}><p className="eyebrow">Participantes</p><h1>Usa apodos, no nombres completos.</h1>{aliases.map((alias, index) => <div className="learner-line" key={learnerIds[index] ?? `new-${index}`}><label>Apodo<input value={alias} onChange={event => setAliases(old => old.map((value, i) => i === index ? event.target.value : value))} maxLength={40}/></label><label>Edad<select value={ageBands[index]} onChange={event => setAgeBands(old => old.map((value, i) => i === index ? event.target.value as typeof value : value))}><option>5-6</option><option>7-8</option><option>9-10</option></select></label>{aliases.length > 1 && <button type="button" className="text-button" onClick={() => removeLearner(index)}>Quitar</button>}</div>)}<button type="button" className="text-button" onClick={() => { if (aliases.length < 4) { setAliases(old => [...old, `Explorer ${old.length + 1}`]); setAgeBands(old => [...old, "7-8"]); setLearnerIds(old => [...old, null]); } }}>+ Añadir participante</button>{error && <p className="error" role="alert">{error}</p>}<button className="button primary block" disabled={busy || aliases.some(alias => !alias.trim())}>{busy ? "Guardando…" : editing ? "Guardar cambios" : "Ver mi primer plan"}</button><small>No pedimos fecha de nacimiento, escuela, foto ni correo del niño.</small></form>}
  </section></div>;
}

function AdultGate({ challenge, onPass, onClose }: { challenge: AdultGateChallenge; onPass: (token: string) => Promise<void>; onClose: () => void }) {
  const [answers, setAnswers] = useState<Record<number, number>>({}), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null);
  const complete = challenge.prompts.every((_, index) => answers[index] !== undefined);
  async function submit() { if (!complete) return; setBusy(true); setError(null); try { const result = await verifyAdultGate(challenge.challengeId, challenge.prompts.map((_, index) => answers[index])); await onPass(result.adultGateToken); } catch (reason) { setError(reason instanceof Error ? reason.message : "Las asociaciones no coinciden."); } finally { setBusy(false); } }
  return <div className="family-modal"><section className="gate-card" role="dialog" aria-modal="true"><button className="modal-close" onClick={onClose}>×</button><div className="gate-icon">12</div><p className="eyebrow">Puerta para adultos</p><h2>Confirma las tres asociaciones</h2><p>Esta fricción ayuda a mantener a un adulto presente. No verifica legalmente la edad.</p>{challenge.prompts.map((question, index) => <fieldset className="gate-question" key={`${question.word}-${index}`}><legend>{question.word}</legend><div>{question.options.map(option => <label className={answers[index] === option ? "selected" : ""} key={option}><input type="radio" name={`q-${index}`} checked={answers[index] === option} onChange={() => setAnswers(old => ({ ...old, [index]: option }))}/>{option}</label>)}</div></fieldset>)}{error && <p className="error" role="alert">{error}</p>}<button className="button primary block" disabled={!complete || busy} onClick={submit}>{busy ? "Comprobando…" : "Desbloquear 15 minutos"}</button></section></div>;
}

function FeedbackModal({ familyId, locale, activityVersionId, sessionId, screen, onClose }: { familyId: string; locale: Locale; activityVersionId?: string; sessionId?: string; screen: string; onClose: () => void }) {
  const [sent, setSent] = useState(false), [useful, setUseful] = useState<boolean | null>(null), [comment, setComment] = useState(""), [category, setCategory] = useState<"product" | "content" | "error" | "safety" | "privacy">("product"), [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); if (useful === null) return; setError(null); try { await sendFamilyFeedback(familyId, { useful, comment, category, activityVersionId, sessionId, screen, locale, appVersion: "web-pilot-v1", browserFamily: navigator.userAgent.slice(0, 70), journeyState: activityVersionId ? "activity" : screen }); setSent(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "No pudimos enviar el comentario."); } }
  return <div className="family-modal"><section className="feedback-card" role="dialog" aria-modal="true"><button className="modal-close" onClick={onClose}>×</button><p className="eyebrow">Piloto familiar</p><h2>¿Cómo va la experiencia?</h2>{sent ? <div className="feedback-thanks"><span>✓</span><strong>Gracias. Tu comentario quedó registrado.</strong><p>Solo se guarda el texto redactado y caduca a los 90 días.</p></div> : <form onSubmit={submit}><label>¿Te resultó útil?</label><div className="useful-choice"><label className={useful === true ? "selected" : ""}><input type="radio" name="useful" onChange={() => setUseful(true)}/>Sí</label><label className={useful === false ? "selected" : ""}><input type="radio" name="useful" onChange={() => setUseful(false)}/>No</label></div><label>Tipo<select value={category} onChange={event => setCategory(event.target.value as typeof category)}><option value="product">Producto</option><option value="content">Contenido</option><option value="error">Error</option><option value="safety">Seguridad</option><option value="privacy">Privacidad</option></select></label><label>Comentario opcional<textarea rows={4} maxLength={1200} value={comment} onChange={event => setComment(event.target.value)} placeholder="Cuéntanos qué funcionó o qué se trabó. No incluyas nombres, correos ni datos del niño."/></label>{error && <p className="error" role="alert">{error}</p>}<button className="button primary block" disabled={useful === null}>Enviar comentario</button></form>}</section></div>;
}

function FamilyHeader({ onFeedback }: { onFeedback: () => void }) { return <header className="family-header"><Brand/><div className="family-header-actions"><span className="pilot-badge">Piloto privado</span><button onClick={onFeedback}>♡ <span>Feedback</span></button><span className="family-avatar">A</span></div></header>; }

function Today({ card, explanation, onStart }: { card: CatalogCard | null; explanation: string[]; onStart: (card: CatalogCard) => void }) { return <div className="family-page"><section className="today-intro"><div><p className="eyebrow">Plan de familia</p><h1>Una idea clara para aprender juntos.</h1><p>Elegida por edad, tiempo, materiales y preferencias. Tú decides si encaja hoy.</p></div><div className="why-card"><span>◎</span><div><strong>¿Por qué esta?</strong><small>{explanation.join(" · ").replaceAll("_", " ") || "Reglas publicadas"}</small></div></div></section>{card ? <Card card={card} onStart={onStart}/> : <section className="journey-empty"><span>○</span><h2>Aún no hay una actividad publicada que encaje</h2><p>El administrador verá este hueco. Ningún borrador se muestra a familias.</p></section>}<section className="family-tip"><span>✦</span><div><strong>La guía siempre funciona sin IA.</strong><p>El acompañante resuelve problemas o propone cambios ya revisados.</p></div></section></div>; }

function Plan({ cards, onStart }: { cards: CatalogCard[]; onStart: (card: CatalogCard) => void }) { return <div className="family-page"><div className="page-heading"><p className="eyebrow">Tu semana</p><h1>Plan flexible</h1><p>Elige otra actividad antes de iniciar. La versión queda fijada al comenzar.</p></div><div className="plan-list">{cards.map((card, index) => <article key={card.activityVersionId}><div className="plan-day"><strong>{["Hoy", "Próxima", "Fin de semana"][index] ?? "Después"}</strong><small>{index ? "Sugerido" : "Listo"}</small></div><Card card={card} compact onStart={onStart}/></article>)}</div></div>; }

function Explore({ cards, onStart }: { cards: CatalogCard[]; onStart: (card: CatalogCard) => void }) { const [filter, setFilter] = useState("Todo"); const filtered = cards.filter(card => filter === "Todo" || filter === "20 min" && card.minutes <= 20 || filter === "Poco desorden" && card.mess === "low" || filter === "1 niño" && card.participants[0] === 1 || filter === "Riesgo A" && card.risk === "A"); return <div className="family-page wide"><div className="page-heading"><p className="eyebrow">Catálogo publicado</p><h1>Explorar actividades</h1><p>Solo mostramos versiones bilingües, revisadas y elegibles.</p></div><div className="filter-row">{["Todo", "20 min", "Poco desorden", "1 niño", "Riesgo A"].map(item => <button className={filter === item ? "active" : ""} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div>{filtered.length ? <div className="catalog-grid">{filtered.map(card => <Card key={card.activityVersionId} card={card} compact onStart={onStart}/>)}</div> : <section className="journey-empty"><h2>Sin resultados publicados</h2><p>Prueba otro filtro.</p></section>}</div>; }

function Journey({ journey }: { journey: JourneyView }) { return <div className="family-page"><div className="page-heading"><p className="eyebrow">Observaciones, no notas</p><h1>Tu recorrido</h1><p>Aquí verás lo que probaron y notaron, sin calificar al niño.</p></div><section className="journey-summary"><div><strong>{journey.completed}</strong><span>actividades cerradas</span></div><div><strong>{journey.completed ? "En curso" : "—"}</strong><span>{journey.completed ? "historial explicable" : "todavía sin tendencia"}</span></div></section>{journey.observations.length ? <section className="family-settings"><h2>Observaciones recientes</h2>{journey.observations.map((item, index) => <article key={item.sessionId ?? index}><span className="learner-avatar">{item.outcome === "worked" ? "✓" : "≈"}</span><div><strong>{item.observation || "Cierre sin comentario"}</strong><small>{item.durationMinutes ?? 0} min · {item.activityVersionId}</small></div></article>)}</section> : <section className="journey-empty"><span>○</span><h2>La primera observación empieza hoy</h2><p>Después de una actividad podrás guardar un cierre de menos de 20 segundos.</p></section>}</div>; }

function FamilySettings({ family, onEdit, onPrivacy }: { family: FamilyProfile; onEdit: () => void; onPrivacy: (action: "export" | "delete") => Promise<void> }) {
  const [message, setMessage] = useState<string | null>(null);const [needsReauth,setNeedsReauth]=useState(false);
  async function privacy(action: "export" | "delete") {
    setMessage("Procesando…");
    try { await onPrivacy(action); setMessage(action === "export" ? "Solicitud de exportación registrada." : "Solicitud de eliminación registrada."); }
    catch { setNeedsReauth(true);setMessage("Necesitamos una autenticación reciente antes de registrar esta solicitud."); }
  }
  async function reauthenticate(){try{await requestReauthentication();setMessage("Enviamos un enlace al correo del adulto. Ábrelo y repite la solicitud.");setNeedsReauth(false)}catch{setMessage("No pudimos enviar el enlace. Inténtalo de nuevo.")}}
  return <div className="family-page"><div className="page-heading"><p className="eyebrow">Control adulto</p><h1>Familia</h1><p>Perfiles mínimos, preferencias y privacidad en un solo lugar.</p></div><section className="family-settings"><h2>Participantes</h2>{family.learners.map((learner, index) => <article key={learner.learnerId}><span className={`learner-avatar ${index % 2 ? "alt" : ""}`}>{learner.alias.split(" ").map(word => word[0]).join("").slice(0, 2)}</span><div><strong>{learner.alias}</strong><small>{learner.ageBand} años · apodo</small></div></article>)}<button className="text-button" onClick={onEdit}>Editar preferencias</button></section><section className="family-settings"><h2>Preferencias</h2><dl><div><dt>Tiempo habitual</dt><dd>{family.preferences.minutes} minutos</dd></div><div><dt>Desorden</dt><dd>{family.preferences.mess}</dd></div><div><dt>Idioma</dt><dd>{family.locale}</dd></div></dl></section><section className="family-settings privacy"><h2>Privacidad y datos</h2><button onClick={() => privacy("export")}>Exportar datos <b>→</b></button><button onClick={() => privacy("delete")}>Solicitar eliminación <b>→</b></button>{needsReauth&&<button className="button secondary" onClick={reauthenticate}>Enviar enlace de reautenticación</button>}<small>Requiere autenticación reciente. {message}</small><nav className="family-policy-links" aria-label="Políticas"><a href="/privacy">Privacidad</a><a href="/terms">Términos</a><a href="/safety">Seguridad</a></nav><button className="text-button" onClick={() => signOut()}>Cerrar sesión</button></section></div>;
}

function Session({ record, experience, onExperienceChanged, onFinish }: { record: FamilySession; experience: ExperienceView; onExperienceChanged: (value: ExperienceView) => void; onFinish: () => Promise<void> }) {
  const initial = Math.max(0, experience.blocks.findIndex(block => block.id === experience.currentBlockId));
  const [index, setIndex] = useState(initial), [closeout, setCloseout] = useState(false), [observation, setObservation] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState<string | null>(null);
  const block = experience.blocks[Math.min(index, experience.blocks.length - 1)], atEnd = index === experience.blocks.length - 1;
  async function move(next: number) { const nextBlock = experience.blocks[next]; if (!nextBlock) return; setBusy(true); try { await updateSessionProgress(record.sessionId, nextBlock.id, "active"); setIndex(next); } catch (reason) { setError(reason instanceof Error ? reason.message : "No pudimos guardar el paso."); } finally { setBusy(false); } }
  async function exitInterrupted() { setBusy(true); try { await updateSessionProgress(record.sessionId, block.id, "interrupted"); } finally { await onFinish(); } }
  async function finish(outcome: "worked" | "partly" | "not_today") { setBusy(true); setError(null); try { const elapsed = Math.max(0, Math.min(180, Math.round((Date.now() - new Date(record.startedAt).getTime()) / 60_000))); await closeFamilySession(record.sessionId, outcome, observation, elapsed); await onFinish(); } catch (reason) { setError(reason instanceof Error ? reason.message : "No pudimos guardar el cierre."); setBusy(false); } }
  if (!block) return <main className="fatal"><h1>Actividad sin pasos publicados</h1><button onClick={onFinish}>Volver</button></main>;
  return <div className="session-shell"><header className="session-header"><button disabled={busy} onClick={exitInterrupted}>← <span>Salir</span></button><div><strong>{experience.title}</strong><small>Versión exacta · {experience.activityVersionId}</small></div><span>{index + 1}/{experience.blocks.length}</span></header><div className="session-progress"><i style={{ width: `${(index + 1) / experience.blocks.length * 100}%` }}/></div><main className="session-main"><div className="session-context"><p className="eyebrow">Paso actual</p><h1>{experience.title}</h1><p>{experience.summary}</p></div><section className="current-block" data-block-id={block.id}>{renderBlock(block)}</section>{error && <p className="error">{error}</p>}<div className="session-actions"><button className="button secondary" disabled={index === 0 || busy} onClick={() => move(index - 1)}>Anterior</button><button className="button primary" disabled={busy} onClick={() => atEnd ? setCloseout(true) : move(index + 1)}>{atEnd ? "Cerrar actividad" : "Siguiente paso"}</button></div></main><Companion experience={experience} onExperienceChanged={onExperienceChanged}/>{closeout && <div className="family-modal"><section className="closeout-card"><button className="modal-close" onClick={() => setCloseout(false)}>×</button><p className="eyebrow">Cierre · menos de 20 segundos</p><h2>¿Cómo resultó hoy?</h2><div className="outcome-grid"><button disabled={busy} onClick={() => finish("worked")}><span>✓</span>Funcionó</button><button disabled={busy} onClick={() => finish("partly")}><span>≈</span>En parte</button><button disabled={busy} onClick={() => finish("not_today")}><span>○</span>Hoy no</button></div><label>Una observación opcional<textarea maxLength={300} rows={2} value={observation} onChange={event => setObservation(event.target.value)} placeholder="Notamos que…"/></label>{error && <p className="error">{error}</p>}<small>Puedes solicitar exportación o eliminación desde Familia.</small></section></div>}</div>;
}

export default function FamilyProductApp() {
  const [authenticated, setAuthenticated] = useState(DEMO_MODE), [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null), [overview, setOverview] = useState<FamilyOverview | null>(null), [catalog, setCatalog] = useState<CatalogCard[]>([]), [tab, setTab] = useState<FamilyTab>("today"), [challenge, setChallenge] = useState<AdultGateChallenge | null>(null), [selected, setSelected] = useState<CatalogCard | null>(null), [sessionRecord, setSessionRecord] = useState<FamilySession | null>(null), [lastSessionId, setLastSessionId] = useState<string | undefined>(), [experience, setExperience] = useState<ExperienceView | null>(null), [feedback, setFeedback] = useState(false), [onboarding, setOnboarding] = useState(() => new URLSearchParams(location.search).get("onboarding") === "1");
  const familyId = overview?.family.familyId ?? localStorage.getItem("kids.family_id") ?? (DEMO_MODE ? DEMO_FAMILY_ID : null);
  async function loadFamily(id: string) { const next = await getFamilyOverview(id), cards = await getCatalog(next.family.locale); setOverview(next); setCatalog(cards); document.documentElement.lang = next.family.locale; localStorage.setItem("kids.family_id", next.family.familyId); }
  useEffect(() => { let active = true; async function initialize() { setLoading(true); setError(null); try { if (!DEMO_MODE) { if (!supabase) throw new Error("Supabase authentication is not configured."); const { data } = await supabase.auth.getSession(); if (!data.session) { if (active) setAuthenticated(false); return; } localStorage.setItem("kids.access_token", data.session.access_token); if (active) setAuthenticated(true); } const stored = localStorage.getItem("kids.family_id") ?? (DEMO_MODE ? DEMO_FAMILY_ID : null); if (stored) await loadFamily(stored); else if (active) setOnboarding(true); } catch (reason) { if (active) { const message = reason instanceof Error ? reason.message : "No pudimos cargar la familia."; if (!DEMO_MODE && /family|404|not found/i.test(message)) setOnboarding(true); else setError(message); } } finally { if (active) setLoading(false); } } initialize(); const listener = supabase?.auth.onAuthStateChange((_event, value) => { if (value) { localStorage.setItem("kids.access_token", value.access_token); setAuthenticated(true); initialize(); } else { localStorage.removeItem("kids.access_token"); localStorage.removeItem("kids.family_id"); setAuthenticated(false); setOverview(null); } }); return () => { active = false; listener?.data.subscription.unsubscribe(); }; }, []);
  const planCards = useMemo(() => overview?.plan?.length ? overview.plan : catalog.slice(0, 3), [overview, catalog]);
  if (!authenticated) return <Login/>;
  if (loading && !overview) return <main className="loading">Preparando tu plan familiar…</main>;
  if (error && !overview && !onboarding) return <main className="fatal"><h1>No pudimos cargar tu familia</h1><p>{error}</p><button onClick={() => location.reload()}>Reintentar</button></main>;
  if (sessionRecord && experience) return <Session record={sessionRecord} experience={experience} onExperienceChanged={setExperience} onFinish={async () => { setLastSessionId(sessionRecord.sessionId); setSessionRecord(null); setExperience(null); setTab("journey"); setFeedback(true); if (familyId) await loadFamily(familyId); }}/>;
  async function completeOnboarding(input: SetupInput) { const family = await setupFamily(input); localStorage.setItem("kids.family_id", family.familyId); await loadFamily(family.familyId); setOnboarding(false); }
  async function begin(card: CatalogCard) { if (!familyId || !overview) return; setError(null); try { setSelected(card); setChallenge(await createAdultGate(familyId, overview.family.locale)); } catch (reason) { setError(reason instanceof Error ? reason.message : "No pudimos preparar la puerta adulta."); } }
  async function passGate(token: string) { if (!selected || !overview || !familyId) return; const participants = overview.family.learners.slice(0, Math.min(4, Math.max(1, overview.family.preferences.participants))).map(item => item.learnerId); const record = await startFamilySession(familyId, selected.activityVersionId, overview.family.locale, token, participants, selected.plannedActivityId); const view = await getExperience(record.contextId); setSessionRecord(record); setExperience(view); setChallenge(null); }
  const page = !overview ? <div className="family-page"><section className="journey-empty"><h2>Completa el perfil familiar</h2></section></div> : tab === "today" ? <Today card={overview.today} explanation={overview.explanation} onStart={begin}/> : tab === "plan" ? <Plan cards={planCards} onStart={begin}/> : tab === "explore" ? <Explore cards={catalog} onStart={begin}/> : tab === "journey" ? <Journey journey={overview.journey}/> : <FamilySettings family={overview.family} onEdit={() => setOnboarding(true)} onPrivacy={action => requestPrivacyAction(overview.family.familyId, action).then(() => undefined)}/>;
  return <div className="family-shell"><FamilyHeader onFeedback={() => setFeedback(true)}/>{error && <div className="app-alert error" role="alert">{error}<button onClick={() => setError(null)}>×</button></div>}<main>{page}</main><nav className="family-nav">{([["today", "⌂", "Hoy"], ["plan", "▤", "Plan"], ["explore", "◇", "Explorar"], ["journey", "↗", "Recorrido"], ["family", "○", "Familia"]] as Array<[FamilyTab, string, string]>).map(([id, icon, label]) => <button className={tab === id ? "active" : ""} key={id} onClick={() => setTab(id)}><i>{icon}</i><span>{label}</span></button>)}</nav>{challenge && <AdultGate challenge={challenge} onPass={passGate} onClose={() => setChallenge(null)}/>} {feedback && familyId && <FeedbackModal familyId={familyId} locale={overview?.family.locale ?? "es-US"} activityVersionId={selected?.activityVersionId} sessionId={lastSessionId} screen={tab} onClose={() => { setFeedback(false); setLastSessionId(undefined); }}/>} {onboarding && <Onboarding initial={overview?.family} onDone={completeOnboarding} onClose={overview ? () => setOnboarding(false) : undefined}/>}</div>;
}
