import { FormEvent, useEffect, useMemo, useState } from "react";
import { getExperience } from "./api";
import { renderBlock } from "./blocks";
import { Companion } from "./Companion";
import { DEMO_CONTEXT_ID } from "./demo";
import type { CatalogCard, ExperienceView, Locale } from "./types";
import { copy } from "./copy";
import { deferAuthStateWork, supabase } from "./auth";
import { Login } from "./Login";

type FamilyTab="today"|"plan"|"explore"|"journey"|"family";
const demoMode=import.meta.env.VITE_DEMO_MODE!=="false";
const familyCards:CatalogCard[]=[
  {activityVersionId:"ACT-0001@1.0.0",title:"Paper Bridge",summary:"Build, test, and improve a paper bridge using the same load each time.",minutes:30,age:[5,10],participants:[1,4],risk:"A",mess:"low"},
  {activityVersionId:"ACT-0002@1.0.0",title:"Seed Sorter",summary:"Invent a sorting rule, test it, and explain what belongs together.",minutes:25,age:[5,10],participants:[1,4],risk:"A",mess:"low"},
  {activityVersionId:"ACT-0004@1.0.0",title:"Balloon Hovercraft",summary:"Compare movement with and without a small cushion of air.",minutes:25,age:[7,10],participants:[1,3],risk:"B",mess:"low"},
  {activityVersionId:"ACT-0005@1.0.0",title:"Water Transporter",summary:"Test tools that move water while keeping the comparison fair.",minutes:25,age:[5,10],participants:[1,4],risk:"A",mess:"medium"},
  {activityVersionId:"ACT-0008@1.0.0",title:"Cargo Ship",summary:"Design a foil boat and measure how much cargo it can hold.",minutes:30,age:[5,10],participants:[1,4],risk:"A",mess:"medium"},
  {activityVersionId:"ACT-0010@1.0.0",title:"Germination Comparison",summary:"Observe how one changed condition affects sprouting seeds.",minutes:20,age:[5,10],participants:[1,4],risk:"A",mess:"low"},
];

function Brand(){return <a className="family-brand" href="/"><span className="brand-mark" aria-hidden="true"><i/><i/><i/></span><span><strong>Kids Learning</strong><small>Grown-up guided</small></span></a>}
function Card({card,compact=false,onStart}:{card:CatalogCard;compact?:boolean;onStart:()=>void}){return <article className={`family-activity-card ${compact?"compact":""}`}><div className={`activity-art art-${Number(card.activityVersionId.slice(7,8))%4}`}><span>{card.title.split(" ").map(word=>word[0]).join("").slice(0,2)}</span><small>{card.mess} mess</small></div><div className="activity-card-body"><div className="card-tags"><span>{card.minutes} min</span><span>{card.age[0]}–{card.age[1]} años</span><span>Riesgo {card.risk}</span></div><h3>{card.title}</h3><p>{card.summary}</p><button className="button primary" onClick={onStart}>{compact?"Ver actividad":"Preparar actividad"}</button></div></article>}

function Onboarding({onDone}:{onDone:()=>void}){const [step,setStep]=useState(0);const [adultLed,setAdultLed]=useState(false);const [aliases,setAliases]=useState(["Explorer 1","Builder 2"]);return <div className="family-modal full"><section className="onboarding-card"><Brand/><div className="onboarding-progress">{[0,1,2].map(index=><i className={index<=step?"active":""} key={index}/>)}</div>{step===0&&<div className="onboarding-step"><p className="eyebrow">Antes de empezar</p><h1>Aprender juntos, con un adulto presente.</h1><p>Kids Learning propone experiencias para hacer en familia. No es una aplicación para que un niño use a solas y no crea cuentas infantiles.</p><label className="consent-row"><input type="checkbox" checked={adultLed} onChange={event=>setAdultLed(event.target.checked)}/><span><strong>Entiendo que un adulto guía cada actividad.</strong><small>La seguridad, los materiales y los cambios siempre requieren supervisión.</small></span></label><button className="button primary block" disabled={!adultLed} onClick={()=>setStep(1)}>Continuar</button></div>}{step===1&&<div className="onboarding-step"><p className="eyebrow">Tu hogar</p><h1>¿Qué suele funcionar en casa?</h1><div className="choice-grid"><button className="selected">30 minutos</button><button>20 minutos</button><button className="selected">Poco desorden</button><button>Desorden medio</button><button className="selected">1–2 niños</button><button>3–4 niños</button></div><p className="privacy-note">Puedes cambiar esto después. Recomendamos con reglas claras; la IA solo explica.</p><button className="button primary block" onClick={()=>setStep(2)}>Guardar preferencias</button></div>}{step===2&&<form className="onboarding-step" onSubmit={event=>{event.preventDefault();localStorage.setItem("kids.onboarded","true");onDone()}}><p className="eyebrow">Participantes</p><h1>Usa apodos, no nombres completos.</h1>{aliases.map((alias,index)=><div className="learner-line" key={index}><label>Apodo<input value={alias} onChange={event=>setAliases(old=>old.map((value,i)=>i===index?event.target.value:value))} maxLength={40}/></label><label>Edad<select defaultValue={index?"7-8":"5-6"}><option>5-6</option><option>7-8</option><option>9-10</option></select></label></div>)}<button type="button" className="text-button" onClick={()=>setAliases(old=>old.length<4?[...old,`Explorer ${old.length+1}`]:old)}>+ Añadir participante</button><button className="button primary block">Ver mi primer plan</button><small>No pedimos fecha de nacimiento, escuela, foto ni correo del niño.</small></form>}</section></div>}

function AdultGate({onPass,onClose}:{onPass:()=>void;onClose:()=>void}){const questions=[{word:"cuatro",value:4,options:[3,4,7]},{word:"siete",value:7,options:[6,7,9]},{word:"dos",value:2,options:[2,5,8]}];const [answers,setAnswers]=useState<Record<number,number>>({});const complete=questions.every((question,index)=>answers[index]===question.value);return <div className="family-modal"><section className="gate-card" role="dialog" aria-modal="true"><button className="modal-close" onClick={onClose}>×</button><div className="gate-icon">12</div><p className="eyebrow">Puerta para adultos</p><h2>Confirma las tres asociaciones</h2><p>Esta pequeña fricción ayuda a mantener a un adulto presente. No verifica legalmente la edad.</p>{questions.map((question,index)=><fieldset className="gate-question" key={question.word}><legend>{question.word}</legend><div>{question.options.map(option=><label className={answers[index]===option?"selected":""} key={option}><input type="radio" name={`q-${index}`} checked={answers[index]===option} onChange={()=>setAnswers(old=>({...old,[index]:option}))}/>{option}</label>)}</div></fieldset>)}<button className="button primary block" disabled={!complete} onClick={onPass}>Desbloquear 15 minutos</button></section></div>}

function FeedbackModal({onClose}:{onClose:()=>void}){const [sent,setSent]=useState(false);function submit(event:FormEvent){event.preventDefault();setSent(true)}return <div className="family-modal"><section className="feedback-card" role="dialog" aria-modal="true"><button className="modal-close" onClick={onClose}>×</button><p className="eyebrow">Piloto familiar</p><h2>¿Cómo va la experiencia?</h2>{sent?<div className="feedback-thanks"><span>✓</span><strong>Gracias. Tu comentario quedó registrado.</strong><p>El texto se revisa para eliminar posibles datos personales y caduca a los 90 días.</p></div>:<form onSubmit={submit}><label>¿Te resultó útil?</label><div className="useful-choice"><label><input type="radio" name="useful" required/>Sí</label><label><input type="radio" name="useful"/>No</label></div><label>Comentario opcional<textarea rows={4} maxLength={1200} placeholder="Cuéntanos qué funcionó o qué se trabó. No incluyas nombres, correos ni datos del niño."/></label><button className="button primary block">Enviar comentario</button></form>}</section></div>}

function FamilyHeader({onFeedback}:{onFeedback:()=>void}){return <header className="family-header"><Brand/><div className="family-header-actions"><span className="pilot-badge">Piloto privado</span><button onClick={onFeedback} aria-label="Enviar feedback">♡ <span>Feedback</span></button><span className="family-avatar">A</span></div></header>}

function Today({onStart}:{onStart:()=>void}){return <div className="family-page"><section className="today-intro"><div><p className="eyebrow">Sábado · plan de familia</p><h1>Una idea clara para aprender juntos.</h1><p>Elegida por edad, tiempo, materiales y preferencias. Tú decides si encaja hoy.</p></div><div className="why-card"><span>◎</span><div><strong>¿Por qué esta?</strong><small>30 min · poco desorden · 2 participantes · materiales comunes</small></div></div></section><Card card={familyCards[0]} onStart={onStart}/><section className="family-tip"><span>✦</span><div><strong>La guía siempre funciona sin IA.</strong><p>El acompañante aparece solo durante la actividad para resolver problemas o proponer cambios revisados.</p></div></section></div>}

function Plan({onStart}:{onStart:()=>void}){return <div className="family-page"><div className="page-heading"><p className="eyebrow">Tu semana</p><h1>Plan flexible</h1><p>Mueve o cambia cualquier actividad antes de iniciarla.</p></div><div className="plan-list">{familyCards.slice(0,3).map((card,index)=><article key={card.activityVersionId}><div className="plan-day"><strong>{["Hoy","Martes","Fin de semana"][index]}</strong><small>{["Listo","Sugerido","Sugerido"][index]}</small></div><Card card={card} compact onStart={onStart}/><button className="plan-more">•••</button></article>)}</div></div>}

function Explore({onStart}:{onStart:()=>void}){const [filter,setFilter]=useState("Todo");return <div className="family-page wide"><div className="page-heading"><p className="eyebrow">Catálogo publicado</p><h1>Explorar actividades</h1><p>Solo mostramos versiones bilingües elegibles para tu familia.</p></div><div className="filter-row">{["Todo","20 min","Poco desorden","1 niño","Riesgo A"].map(item=><button className={filter===item?"active":""} onClick={()=>setFilter(item)} key={item}>{item}</button>)}</div><div className="catalog-grid">{familyCards.filter(card=>filter==="Todo"||filter==="20 min"&&card.minutes<=20||filter==="Poco desorden"&&card.mess==="low"||filter==="1 niño"&&card.participants[0]===1||filter==="Riesgo A"&&card.risk==="A").map(card=><Card key={card.activityVersionId} card={card} compact onStart={onStart}/>)}</div></div>}

function Journey(){return <div className="family-page"><div className="page-heading"><p className="eyebrow">Observaciones, no notas</p><h1>Tu recorrido</h1><p>Aquí verás lo que probaron, notaron y quisieron repetir.</p></div><section className="journey-summary"><div><strong>0</strong><span>actividades cerradas</span></div><div><strong>—</strong><span>todavía sin tendencia</span></div></section><section className="journey-empty"><span>○</span><h2>La primera observación empieza hoy</h2><p>Después de una actividad podrás guardar un cierre de menos de 20 segundos. Siempre podrás corregirlo o eliminarlo.</p></section></div>}

function FamilySettings(){return <div className="family-page"><div className="page-heading"><p className="eyebrow">Control adulto</p><h1>Familia</h1><p>Perfiles mínimos, preferencias y privacidad en un solo lugar.</p></div><section className="family-settings"><h2>Participantes</h2><article><span className="learner-avatar">E1</span><div><strong>Explorer 1</strong><small>5–6 años · apodo</small></div><button>Editar</button></article><article><span className="learner-avatar alt">B2</span><div><strong>Builder 2</strong><small>7–8 años · apodo</small></div><button>Editar</button></article></section><section className="family-settings"><h2>Preferencias</h2><dl><div><dt>Tiempo habitual</dt><dd>30 minutos</dd></div><div><dt>Desorden</dt><dd>Bajo</dd></div><div><dt>Idioma</dt><dd>Español (US)</dd></div></dl></section><section className="family-settings privacy"><h2>Privacidad y datos</h2><button>Exportar datos <b>→</b></button><button>Corregir información <b>→</b></button><button>Solicitar eliminación <b>→</b></button><small>Estas acciones requieren volver a autenticar al adulto.</small></section></div>}

function Session({experience,onExperienceChanged,onExit}:{experience:ExperienceView;onExperienceChanged:(value:ExperienceView)=>void;onExit:()=>void}){const [index,setIndex]=useState(0);const [closeout,setCloseout]=useState(false);const block=experience.blocks[Math.min(index,experience.blocks.length-1)];const atEnd=index===experience.blocks.length-1;return <div className="session-shell"><header className="session-header"><button onClick={onExit}>← <span>Salir</span></button><div><strong>{experience.title}</strong><small>Versión exacta · {experience.activityVersionId}</small></div><span>{index+1}/{experience.blocks.length}</span></header><div className="session-progress"><i style={{width:`${(index+1)/experience.blocks.length*100}%`}}/></div><main className="session-main"><div className="session-context"><p className="eyebrow">Paso actual</p><h1>{experience.title}</h1><p>{experience.summary}</p></div><section className="current-block" data-block-id={block.id}>{renderBlock(block)}</section><div className="session-actions"><button className="button secondary" disabled={index===0} onClick={()=>setIndex(value=>Math.max(0,value-1))}>Anterior</button><button className="button primary" onClick={()=>atEnd?setCloseout(true):setIndex(value=>value+1)}>{atEnd?"Cerrar actividad":"Siguiente paso"}</button></div></main><Companion experience={experience} onExperienceChanged={onExperienceChanged}/>{closeout&&<div className="family-modal"><section className="closeout-card"><p className="eyebrow">Cierre · menos de 20 segundos</p><h2>¿Cómo resultó hoy?</h2><div className="outcome-grid"><button onClick={onExit}><span>✓</span>Funcionó</button><button onClick={onExit}><span>≈</span>En parte</button><button onClick={onExit}><span>○</span>Hoy no</button></div><label>Una observación opcional<textarea maxLength={300} rows={2} placeholder="Notamos que…"/></label><small>Puedes corregir o borrar esta observación desde Recorrido.</small></section></div>}</div>}

export default function FamilyApp(){const [experience,setExperience]=useState<ExperienceView|null>(null);const [error,setError]=useState<string|null>(null);const [authenticated,setAuthenticated]=useState(demoMode);const [tab,setTab]=useState<FamilyTab>("today");const [gate,setGate]=useState(false);const [session,setSession]=useState(false);const [feedback,setFeedback]=useState(false);const [onboarding,setOnboarding]=useState(()=>new URLSearchParams(location.search).get("onboarding")==="1");
  useEffect(()=>{let active=true;async function initialize(){if(!demoMode){if(!supabase){setError("Supabase authentication is not configured.");return}const{data}=await supabase.auth.getSession();if(!data.session){setAuthenticated(false);return}localStorage.setItem("kids.access_token",data.session.access_token);setAuthenticated(true)}const params=new URLSearchParams(location.search);const contextId=params.get("context")??import.meta.env.VITE_DEFAULT_CONTEXT_ID??import.meta.env.VITE_DEMO_CONTEXT_ID??DEMO_CONTEXT_ID;getExperience(contextId).then(value=>{if(active){document.documentElement.lang=value.locale;setExperience(value)}}).catch(reason=>{if(active)setError(reason instanceof Error?reason.message:"Unable to load activity")})}void initialize();const listener=supabase?.auth.onAuthStateChange((_event,value)=>{if(value){localStorage.setItem("kids.access_token",value.access_token);setAuthenticated(true);deferAuthStateWork(initialize)}else{localStorage.removeItem("kids.access_token");setAuthenticated(false)}});return()=>{active=false;listener?.data.subscription.unsubscribe()}},[]);
  if(!authenticated)return <Login/>;if(error)return <main className="fatal"><h1>Actividad no disponible</h1><p>{error}</p></main>;if(!experience)return <main className="loading">Preparando tu plan familiar…</main>;if(session)return <Session experience={experience} onExperienceChanged={setExperience} onExit={()=>{setSession(false);setTab("journey")}}/>;
  function begin(){setGate(true)}function pass(){setGate(false);setSession(true)}const page=tab==="today"?<Today onStart={begin}/>:tab==="plan"?<Plan onStart={begin}/>:tab==="explore"?<Explore onStart={begin}/>:tab==="journey"?<Journey/>:<FamilySettings/>;
  return <div className="family-shell"><FamilyHeader onFeedback={()=>setFeedback(true)}/><main>{page}</main><nav className="family-nav">{([["today","⌂","Hoy"],["plan","▤","Plan"],["explore","◇","Explorar"],["journey","↗","Recorrido"],["family","○","Familia"]] as Array<[FamilyTab,string,string]>).map(([id,icon,label])=><button className={tab===id?"active":""} key={id} onClick={()=>setTab(id)}><i>{icon}</i><span>{label}</span></button>)}</nav>{gate&&<AdultGate onPass={pass} onClose={()=>setGate(false)}/>} {feedback&&<FeedbackModal onClose={()=>setFeedback(false)}/>} {onboarding&&<Onboarding onDone={()=>setOnboarding(false)}/>}</div>;
}
